### ISSUE TITLE
Thread Limit 

### ISSUE THREAD

**Issue by jan-janssen** [dnoeger/sqsgenerator#3]
When I try to limit the number of threads used I get the following error: 

```
sqsgenerator/core/base.pyx in sqsgenerator.core.base.BaseIterator.__cinit__()

TypeError: __cinit__() got an unexpected keyword argument 'num_threads'
```

**Comment by dnoeger** [comment]
Many thanks, for the report should be fixed (112a56d8b151574b7e87de59d3196d42bc405ae6)
